services:
  umami:
    image: docker.umami.dev/umami-software/umami:mysql-latest
    depends_on:
      - umami-db
    environment:
      DATABASE_TYPE: mysql
    ports:
      - "127.0.0.1:${PORT_UMAMI}:3000"
    networks:
      - umami
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  umami-db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE_NAME}
    volumes:
      - /var/lib/umami-mysql:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - umami

networks:
  umami:
