services:
  umami:
    image: docker.umami.is/umami-software/umami:3
    restart: unless-stopped
    depends_on:
      - umami-db
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@umami-db/${DB_DATABASE_NAME}"
    ports:
      - "127.0.0.1:${PORT_UMAMI}:3000"
    networks:
      - umami
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  umami-db:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - /var/lib/umami/postgres:/var/lib/postgresql:Z
    networks:
      - umami
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  umami:
